# Generated by Django 3.2.4 on 2021-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210609_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpost',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
